#!/usr/bin/env python3
"""
Generate updated ImplementedAPIs markdown file for Flutter Android app.
This is specifically for the Android/Flutter project, NOT the iOS Swift project.
"""

import json
from pathlib import Path
from collections import defaultdict
from datetime import datetime

def load_audit_report():
    """Load the audit report generated by audit_flutter_apis.py."""
    report_path = Path(__file__).parent.parent / 'audit_report.json'
    with open(report_path, 'r') as f:
        return json.load(f)

def generate_markdown_doc(report):
    """Generate the ImplementedAPIs markdown document."""
    
    # Group operations by surface
    by_surface = defaultdict(list)
    for op in report['operations']:
        if not op['is_admin']:  # Exclude admin APIs
            by_surface[op['surface']].append(op)
    
    # Generate markdown
    md = []
    md.append("# Kumele Flutter Android — Implemented APIs")
    md.append("")
    md.append(f"**Audit Date:** {datetime.now().strftime('%Y-%m-%d')}")
    md.append("")
    md.append("This document tracks API implementation status in the **Kumele Flutter Android application**.")
    md.append("")
    md.append("## Important")
    md.append("")
    md.append("This is **NOT** the iOS/Swift project documentation. This tracks the **Flutter/Android** implementation.")
    md.append("")
    md.append("The iOS Swift project has its own separate API tracking document at `AI/05_ImplementedAPIs.md` which tracks the Swift/iOS implementation.")
    md.append("")
    md.append("## Summary")
    md.append("")
    md.append(f"- **Total API Operations:** {report['total_operations']}")
    md.append(f"- **Consumer-Relevant:** {report['consumer_relevant']}")
    md.append(f"- **Admin/Business-Only (Excluded):** {report['admin_only']}")
    md.append(f"- **Implemented:** {report['implemented']}")
    md.append(f"  - With UI Integration: {report['ui_integrated']}")
    md.append(f"  - Without UI: {report['no_ui']}")
    md.append(f"- **Not Implemented:** {report['not_implemented']}")
    md.append("")
    md.append("## Status Legend")
    md.append("")
    md.append("- 🟢 **Implemented & Live** — API call exists and is used in the app")
    md.append("- ⚪ **Implemented but No UI** — API method exists but has no UI integration")
    md.append("- ❌ **Not Implemented** — No implementation exists")
    md.append("- 🚫 **Admin/Business Only** — Excluded from consumer app (not needed)")
    md.append("")
    md.append("---")
    md.append("")
    
    # Surface order for logical grouping
    surface_order = [
        'auth', 'profile', 'hobbies', 'events', 'chat', 'blogs',
        'notifications', 'subscriptions', 'payments', 'tickets',
        'web3', 'ads', 'media', 'legal', 'localization', 'translation',
        'privacy', 'support', 'cart', 'products', 'discounts', 'refunds',
        'share', 'cms', 'app', 'health'
    ]
    
    for surface in surface_order:
        if surface not in by_surface or len(by_surface[surface]) == 0:
            continue
            
        ops = by_surface[surface]
        stats = report['by_surface'][surface]
        
        md.append(f"## {stats['total']}. {surface.upper()}")
        md.append("")
        md.append(f"**Status:** {stats['implemented']}/{stats['total']} implemented "
                  f"({stats['missing']} missing, {stats['admin_only']} admin-only)")
        md.append("")
        md.append("| Status | Method | Endpoint | Summary |")
        md.append("|--------|--------|----------|---------|")
        
        for op in sorted(ops, key=lambda x: x['path']):
            status = op['status']
            method = op['method']
            path = op['path']
            summary = op['summary'][:80] + '...' if len(op['summary']) > 80 else op['summary']
            md.append(f"| {status} | {method} | `{path}` | {summary} |")
        
        md.append("")
    
    md.append("---")
    md.append("")
    md.append("## Implementation Notes")
    md.append("")
    md.append("### General Architecture")
    md.append("")
    md.append("- **API Client:** `lib/shared/services/api_service/api_service.dart`")
    md.append("- **Generated Catalog:** `lib/shared/services/api_service/generated/generated_api_catalog.dart`")
    md.append("- **Repositories:** `lib/features/*/data/repositories/`")
    md.append("- **Remote Data Sources:** `lib/features/*/data/datasources/`")
    md.append("")
    md.append("### Key Implemented Features")
    md.append("")
    md.append("1. **Authentication (16/24 endpoints)**")
    md.append("   - Email/password login and signup")
    md.append("   - Firebase/Google authentication")
    md.append("   - Passkey authentication (login)")
    md.append("   - 2FA setup, enable, disable, verify")
    md.append("   - Password reset flow (forgot, verify OTP, reset)")
    md.append("   - Email verification")
    md.append("")
    md.append("2. **Events (8/25 endpoints)**")
    md.append("   - List events with filters")
    md.append("   - Get event recommendations/matches")
    md.append("   - Create events")
    md.append("   - Join events")
    md.append("   - Chat rooms")
    md.append("")
    md.append("3. **Subscriptions (5/6 endpoints)**")
    md.append("   - Get subscription tiers")
    md.append("   - Get subscription status")
    md.append("   - Create, cancel, resume subscriptions")
    md.append("")
    md.append("4. **Profile & Social (6/20 endpoints)**")
    md.append("   - Get/update user profile")
    md.append("   - Follow/unfollow users")
    md.append("   - Get followers/following")
    md.append("")
    md.append("5. **Payments (7/15 endpoints)**")
    md.append("   - PayPal order creation and capture")
    md.append("   - Payment history")
    md.append("   - Saved cards management")
    md.append("")
    md.append("### Major Missing Features")
    md.append("")
    md.append("1. **Blog System (7/8 endpoints missing)**")
    md.append("   - Only blog feed is implemented")
    md.append("   - Missing: blog detail, comments, likes")
    md.append("")
    md.append("2. **Cart & Products (All endpoints missing)**")
    md.append("   - No shopping cart implementation")
    md.append("   - No product catalog")
    md.append("")
    md.append("3. **Support & Tickets (All endpoints missing)**")
    md.append("   - No support ticket system")
    md.append("   - No help/FAQ integration")
    md.append("")
    md.append("4. **Event Management (17/25 endpoints missing)**")
    md.append("   - Missing: ratings, reports, check-in, guest management")
    md.append("")
    md.append("5. **Notifications (4/6 endpoints missing)**")
    md.append("   - Missing: mark as read, mark all as read, test notifications")
    md.append("")
    md.append("6. **Privacy & GDPR (4/5 endpoints missing)**")
    md.append("   - Only account deletion implemented")
    md.append("   - Missing: data export, consent management, rectification")
    md.append("")
    md.append("### Recommendations")
    md.append("")
    md.append("#### High Priority (Core User Experience)")
    md.append("")
    md.append("1. **Blog Detail & Interaction** - Users can see feed but can't read posts")
    md.append("2. **Event Ratings & Reviews** - Critical for social proof")
    md.append("3. **Notifications Read Status** - Basic UX requirement")
    md.append("4. **Profile Completeness** - Better onboarding")
    md.append("")
    md.append("#### Medium Priority (Enhanced Features)")
    md.append("")
    md.append("1. **Event Check-in** - Host/guest experience")
    md.append("2. **Guest Tickets** - Event attendance tracking")
    md.append("3. **Refunds** - Payment dispute handling")
    md.append("4. **Support Tickets** - User support system")
    md.append("")
    md.append("#### Low Priority (Nice to Have)")
    md.append("")
    md.append("1. **Shopping Cart** - If product sales are planned")
    md.append("2. **NFT Integration** - If web3 features are prioritized")
    md.append("3. **Translation/Localization** - For international expansion")
    md.append("4. **CMS Integration** - For dynamic content")
    md.append("")
    md.append("---")
    md.append("")
    md.append(f"**Generated:** {datetime.now().isoformat()}")
    md.append("")
    md.append("**Note:** This audit was performed by automated analysis of the Flutter codebase.")
    md.append("Actual runtime behavior and UI integration may require manual verification.")
    md.append("")
    
    return '\n'.join(md)

def main():
    print("📝 Generating ImplementedAPIs documentation...")
    
    report = load_audit_report()
    markdown = generate_markdown_doc(report)
    
    # Save to AI directory
    output_path = Path(__file__).parent.parent / 'AI' / 'ImplementedAPIs.md'
    output_path.write_text(markdown)
    
    print(f"✅ Documentation generated: {output_path}")
    print(f"\n📊 Summary:")
    print(f"   - Total APIs: {report['total_operations']}")
    print(f"   - Implemented: {report['implemented']}")
    print(f"   - Missing: {report['not_implemented']}")
    print(f"   - Admin-only (excluded): {report['admin_only']}")

if __name__ == '__main__':
    main()
